### ISSUE TITLE
Back to string

### ISSUE THREAD

**Issue by hoshsadiq** [jonwinton/ddqp#14]
Is there a way to turn a MetricMonitor or other structs back into a string?

**Comment by jonwinton** [comment]
Hey! Sorry for the slow response, this is a fun side project for me and I haven't worked on it in a few weeks. I thought I committed a ToString method, but I could have only done it locally. I'll try and confirm a little later and get back to you

**Comment by hoshsadiq** [comment]
Thanks! If not, I'd be happy to try to implement it, but might need some direction on how it all fits together.

**Comment by jonwinton** [comment]
@hoshsadiq sorry for the delay, but this change should work for you: https://github.com/jonwinton/ddqp/pull/23

**Comment by hoshsadiq** [comment]
Thanks for that. I've not really had a chance to look into it, and won't have for a while, but the code looks like it's what I need anyway. Will close it for now, and raise a new ticket if I need to. Thanks very much.
